Console.WriteLine("    _____         ___________        ____________      ____________       _____         ");
Console.WriteLine("  /      |_       \\          \\       \\           \\    /            \\    /      |_       ");
Console.WriteLine(" /         \\       \\    /\\    \\       \\           \\  |\\___/\\  \\___/|   /         \\      ");
Console.WriteLine("|     /\\    \\       |   \\_\\    |       |    /\\     |  \\|____\\  \\___|  |     /\\    \\     ");
Console.WriteLine("|    |  |    \\      |      ___/        |   |  |    |        |  |      |    |  |    \\    ");
Console.WriteLine("|     \\/      \\     |      \\  ____     |    \\/     |   __  /   / __   |     \\/      \\   ");
Console.WriteLine("|\\      /\\     \\   /     /\\ \\/    \\   /           /|  /  \\/   /_/  |  |\\      /\\     \\  ");
Console.WriteLine("| \\_____\\ \\_____\\ /_____/ |\\______|  /___________/ | |____________/|  | \\_____\\ \\_____\\ ");
Console.WriteLine("| |     | |     | |     | | |     | |           | /  |           | /  | |     | |     | ");
Console.WriteLine(" \\|_____|\\|_____| |_____|/ \\|_____| |___________|/   |___________|/   |_|_____| |_____|");

Console.Write("What is the name of your character? ");
string Player = Console.ReadLine();
int PlayerDefense = 5;
int PlayerStrength = 10;
int PlayerMaxHealth = PlayerStrength * PlayerDefense * 2;
int PlayerHealth = PlayerMaxHealth;
int PlayerMana = 30;
int PlayerLevel = 1;
double  PlayerExp = 0;
decimal PlayerGold = 0;
int WeaponDamage = 5;
int PlayerAttackDamage = PlayerStrength + WeaponDamage;
int PlayerSpecialAttackDmg = PlayerAttackDamage * 2;

Console.WriteLine ("+--------------------------------+");
Console.WriteLine("| \t ARDIA");
Console.WriteLine ("+--------------------------------+");
Console.WriteLine($"| Player Name: {Player} ");
Console.WriteLine($"| Gold: {PlayerGold} ");
Console.WriteLine($"| Experience: {PlayerExp} ");
Console.WriteLine($"| Level: {PlayerLevel} ");
Console.WriteLine ("+--------------------------------+");
Console.WriteLine($"| Health: {PlayerHealth} / {PlayerMaxHealth} ");
Console.WriteLine($"| Strength: {PlayerStrength} ");
Console.WriteLine($"| Defense: {PlayerDefense} ");
Console.WriteLine($"| Mana: {PlayerMana} ");
Console.WriteLine($"| Attack Damage: {PlayerAttackDamage} ");
Console.WriteLine($"| Special Attack Damage: {PlayerSpecialAttackDmg} ");
Console.WriteLine ("+--------------------------------+");
